#!/usr/bin/env python3
"""
Multi-source domain list updater for glocker config file.

This script supports updating domain blocklists from multiple sources,
each with custom fetching and parsing logic. The script is idempotent
and checks timestamps to avoid redundant updates.

Usage:
    ./update_domains.py          - List all available sources
    ./update_domains.py <id>     - Update from specific source
    ./update_domains.py all      - Update from all sources sequentially
    ./update_domains.py strip    - Remove all managed sources (keeps manual domains)
"""

import json
import os
import re
import sys
import urllib.request
from typing import Optional, Tuple, List, Dict, Callable

# Constants
CONFIG_FILE = "conf/conf.yaml"
# Each source's blocklist is generated into its own file here and pulled into
# conf.yaml with `!include conf.d/<file>`. Keeping the big lists out of conf.yaml
# keeps the hand-edited config small.
CONFD_DIR = "conf/conf.d"

# Domains containing any of these substrings (case-insensitive) will be excluded
# from all sources during processing.
EXCLUDED_DOMAIN_SUBSTRINGS = [
    "mullvad",
    "customeriomail.com",
]


## Utility Functions

def fetch_url(url: str) -> bytes:
    """Fetch content from a URL."""
    try:
        with urllib.request.urlopen(url, timeout=30) as response:
            return response.read()
    except Exception as e:
        print(f"Error fetching {url}: {e}", file=sys.stderr)
        sys.exit(1)


def confd_path(source: Dict) -> str:
    """Path to a source's generated blocklist file under conf.d/."""
    return os.path.join(CONFD_DIR, source['file'])


def read_source_timestamp(path: str) -> Optional[str]:
    """Read the '# Last updated: TIMESTAMP' header from a conf.d file (for the
    idempotency check). Returns None if the file is absent or has no header."""
    try:
        with open(path, 'r') as f:
            head = f.read(4096)
    except FileNotFoundError:
        return None
    match = re.search(r'# Last updated: ([0-9T:\-Z]+)', head)
    return match.group(1) if match else None


def write_source_file(source: Dict, formatted_domains: str, timestamp: str, count: int) -> None:
    """Write one source's blocklist to its conf.d file as a standalone YAML
    sequence, with a header recording the source and update time. conf.yaml pulls
    it in via `!include conf.d/<file>`."""
    os.makedirs(CONFD_DIR, exist_ok=True)
    header = (
        f"{source['marker']}. Blocked 24/7\n"
        f"# Last updated: {timestamp} ({count} domains)\n"
        f"# Generated by update_domains.py — do not edit; pulled into conf.yaml via !include.\n"
        f"\n"
    )
    with open(confd_path(source), 'w') as f:
        f.write(header)
        f.write(formatted_domains)
        f.write("\n")

## Source-Specific Functions: Bon Appetit Porn Domains

def fetch_bon_appetit() -> Tuple[List[str], str, Dict]:
    """
    Fetch Bon Appetit porn domains list.
    Returns: (domains_list, timestamp, metadata_dict)
    """
    META_URL = "https://raw.githubusercontent.com/Bon-Appetit/porn-domains/refs/heads/main/meta.json"
    BASE_URL = "https://raw.githubusercontent.com/Bon-Appetit/porn-domains/refs/heads/main/"

    # Step 1: Fetch metadata
    print("  Fetching metadata...")
    content = fetch_url(META_URL)

    try:
        meta = json.loads(content.decode('utf-8'))
    except json.JSONDecodeError as e:
        print(f"  Error parsing meta.json: {e}", file=sys.stderr)
        sys.exit(1)

    # Extract blocklist info
    if 'blocklist' not in meta:
        print("  Error: 'blocklist' not found in meta.json", file=sys.stderr)
        sys.exit(1)

    blocklist = meta['blocklist']
    filename = blocklist.get('name')
    timestamp = blocklist.get('updated')
    lines_count = blocklist.get('lines', 0)

    if not filename or not timestamp:
        print("  Error: Missing required fields in blocklist metadata", file=sys.stderr)
        sys.exit(1)

    print(f"  Current blocklist: {filename}")
    print(f"  Last updated: {timestamp} ({lines_count} domains)")

    # Step 2: Download blocklist
    url = BASE_URL + filename
    print(f"  Downloading blocklist...")

    content = fetch_url(url)
    domains = []

    for line in content.decode('utf-8').splitlines():
        domain = line.strip()
        if domain:  # Skip empty lines
            domains.append(domain)

    if not domains:
        print("  Error: Downloaded blocklist is empty", file=sys.stderr)
        sys.exit(1)

    metadata = {
        'filename': filename,
        'count': len(domains),
        'lines_count': lines_count
    }

    return domains, timestamp, metadata


def parse_bon_appetit(domain: str) -> str:
    """Format domain in compact JSON YAML format."""
    return f'  - {{"name": "{domain}"}}'


## Source-Specific Functions: StevenBlack Hosts

def fetch_stevenblack() -> Tuple[List[str], str, Dict]:
    """
    Fetch StevenBlack unified hosts list.
    Returns: (domains_list, timestamp, metadata_dict)
    """
    HOSTS_URL = "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"

    # Download hosts file
    print("  Fetching hosts file...")
    content = fetch_url(HOSTS_URL)

    # Parse header for metadata
    lines = content.decode('utf-8').splitlines()
    timestamp = None
    total_entries = None
    domains = []

    for line in lines:
        line = line.strip()

        # Extract date from header
        if line.startswith('# Date:'):
            # Format: # Date: 19 December 2025 21:22:56 (UTC)
            date_str = line.replace('# Date:', '').strip()
            # Convert to ISO8601 format
            try:
                from datetime import datetime
                # Parse the date string
                date_str_clean = date_str.replace('(UTC)', '').strip()
                dt = datetime.strptime(date_str_clean, '%d %B %Y %H:%M:%S')
                timestamp = dt.strftime('%Y-%m-%dT%H:%M:%SZ')
            except Exception as e:
                print(f"  Warning: Could not parse date: {e}", file=sys.stderr)
                timestamp = date_str

        # Extract total entries count
        elif line.startswith('# Number of unique domains:'):
            match = re.search(r'# Number of unique domains:\s*([\d,]+)', line)
            if match:
                total_entries = int(match.group(1).replace(',', ''))

        # Parse domain entries (format: 0.0.0.0 domain.name)
        elif line and not line.startswith('#') and line.startswith('0.0.0.0 '):
            parts = line.split()
            if len(parts) >= 2:
                domain = parts[1].strip()
                # Skip localhost entries
                if domain not in ['localhost', 'localhost.localdomain', 'local',
                                'broadcasthost', '0.0.0.0']:
                    domains.append(domain)

    if not timestamp:
        print("  Error: Could not extract timestamp from hosts file", file=sys.stderr)
        sys.exit(1)

    if not domains:
        print("  Error: No domains found in hosts file", file=sys.stderr)
        sys.exit(1)

    print(f"  Last updated: {timestamp} ({len(domains)} domains)")

    metadata = {
        'count': len(domains),
        'total_entries': total_entries or len(domains)
    }

    return domains, timestamp, metadata


def parse_stevenblack(domain: str) -> str:
    """Format domain in compact JSON YAML format."""
    return f'  - {{\"name\": \"{domain}\"}}'


## Source-Specific Functions: HaGeZi DoH/VPN/TOR/Proxy Bypass

def fetch_hagezi() -> Tuple[List[str], str, Dict]:
    """
    Fetch HaGeZi DoH/VPN/TOR/Proxy Bypass blocklist.
    Returns: (domains_list, timestamp, metadata_dict)
    """
    BLOCKLIST_URL = "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/doh-vpn-proxy-bypass-onlydomains.txt"

    # Download blocklist
    print("  Fetching blocklist...")
    content = fetch_url(BLOCKLIST_URL)

    # Parse file
    lines = content.decode('utf-8').splitlines()
    timestamp = None
    version = None
    entry_count = None
    domains = []

    for line in lines:
        line = line.strip()

        # Extract metadata from header
        if line.startswith('# Last modified:'):
            # Format: # Last modified: 23 Dec 2025 10:32 UTC
            date_str = line.replace('# Last modified:', '').strip()
            try:
                from datetime import datetime
                # Parse the date string
                dt = datetime.strptime(date_str, '%d %b %Y %H:%M %Z')
                timestamp = dt.strftime('%Y-%m-%dT%H:%M:%SZ')
            except Exception as e:
                print(f"  Warning: Could not parse date: {e}", file=sys.stderr)
                timestamp = date_str

        elif line.startswith('# Version:'):
            version = line.replace('# Version:', '').strip()

        elif line.startswith('# Number of entries:'):
            match = re.search(r'# Number of entries:\s*(\d+)', line)
            if match:
                entry_count = int(match.group(1))

        # Parse domain entries (non-comment, non-empty lines)
        elif line and not line.startswith('#'):
            domains.append(line)

    if not timestamp:
        print("  Error: Could not extract timestamp from blocklist", file=sys.stderr)
        sys.exit(1)

    if not domains:
        print("  Error: No domains found in blocklist", file=sys.stderr)
        sys.exit(1)

    print(f"  Last updated: {timestamp} ({len(domains)} domains)")

    metadata = {
        'count': len(domains),
        'version': version,
        'original_count': entry_count or len(domains)
    }

    return domains, timestamp, metadata


def parse_hagezi(domain: str) -> str:
    """Format domain in compact JSON YAML format."""
    return f'  - {{\"name\": \"{domain}\"}}'


## Source-Specific Functions: ShadowWhisperer Tunnels (VPNs & Proxies)

def fetch_shadowwhisperer() -> Tuple[List[str], str, Dict]:
    """
    Fetch ShadowWhisperer Tunnels blocklist (VPNs & Proxies).
    Returns: (domains_list, timestamp, metadata_dict)
    """
    BLOCKLIST_URL = "https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Tunnels"

    # Download blocklist
    print("  Fetching blocklist...")
    content = fetch_url(BLOCKLIST_URL)

    # Parse file (plain text, one domain per line, # comments for headers)
    lines = content.decode('utf-8').splitlines()
    timestamp = None
    domain_count_header = None
    domains = []

    for line in lines:
        line = line.strip()

        # Extract metadata from header comments
        # Format: # Updated: 2/2/2026  09:11 (9:11 AM CST)
        if line.startswith('# Updated:'):
            date_str = line.replace('# Updated:', '').strip()
            try:
                from datetime import datetime
                # Remove the parenthetical timezone note
                date_str_clean = re.sub(r'\s*\(.*\)\s*$', '', date_str)
                # Normalize multiple spaces
                date_str_clean = re.sub(r'\s+', ' ', date_str_clean).strip()
                dt = datetime.strptime(date_str_clean, '%m/%d/%Y %H:%M')
                timestamp = dt.strftime('%Y-%m-%dT%H:%M:%SZ')
            except Exception as e:
                print(f"  Warning: Could not parse date: {e}", file=sys.stderr)
                timestamp = date_str

        # Format: # Domains: 1,008
        elif line.startswith('# Domains:'):
            match = re.search(r'# Domains:\s*([\d,]+)', line)
            if match:
                domain_count_header = int(match.group(1).replace(',', ''))

        # Parse domain entries (non-comment, non-empty lines)
        elif line and not line.startswith('#'):
            domains.append(line)

    if not timestamp:
        print("  Error: Could not extract timestamp from blocklist", file=sys.stderr)
        sys.exit(1)

    if not domains:
        print("  Error: No domains found in blocklist", file=sys.stderr)
        sys.exit(1)

    print(f"  Last updated: {timestamp} ({len(domains)} domains)")

    metadata = {
        'count': len(domains),
        'header_count': domain_count_header or len(domains)
    }

    return domains, timestamp, metadata


def parse_shadowwhisperer(domain: str) -> str:
    """Format domain in compact JSON YAML format."""
    return f'  - {{\"name\": \"{domain}\"}}'


## Source Registry
SOURCES = [
    {
        'id': 1,
        'name': 'Bon Appetit Porn Domains',
        'description': 'Comprehensive adult content blocklist',
        'marker': '# Domains from https://github.com/Bon-Appetit/porn-domains',
        'file': 'domains-bon-appetit.yaml',
        'fetch_func': fetch_bon_appetit,
        'parse_func': parse_bon_appetit,
    },
    {
        'id': 2,
        'name': 'StevenBlack Unified Hosts',
        'description': 'Unified hosts file with ads and malware domains',
        'marker': '# Domains from https://github.com/StevenBlack/hosts',
        'file': 'domains-stevenblack.yaml',
        'fetch_func': fetch_stevenblack,
        'parse_func': parse_stevenblack,
    },
    {
        'id': 3,
        'name': 'HaGeZi DoH/VPN/TOR/Proxy Bypass',
        'description': 'Blocks encrypted DNS, VPN, TOR, and proxy bypass methods',
        'marker': '# Domains from https://github.com/hagezi/dns-blocklists (DoH/VPN/TOR/Proxy Bypass)',
        'file': 'domains-hagezi.yaml',
        'fetch_func': fetch_hagezi,
        'parse_func': parse_hagezi,
    },
    {
        'id': 4,
        'name': 'ShadowWhisperer Tunnels (VPNs & Proxies)',
        'description': 'Blocks VPN services and web proxy/unblocker sites',
        'marker': '# Domains from https://github.com/ShadowWhisperer/BlockLists (Tunnels)',
        'file': 'domains-shadowwhisperer.yaml',
        'fetch_func': fetch_shadowwhisperer,
        'parse_func': parse_shadowwhisperer,
    },
    # Add more sources here following the same pattern
]


## Generic Source Update Logic

def get_source_by_id(source_id: int) -> Optional[Dict]:
    """Get source definition by ID."""
    for source in SOURCES:
        if source['id'] == source_id:
            return source
    return None


def update_source(source_id: int) -> str:
    """
    Update domains from a specific source.
    Returns: 'updated', 'skipped', or raises SystemExit on error
    """
    # Step 1: Find source
    source = get_source_by_id(source_id)
    if not source:
        print(f"Error: Source ID {source_id} not found", file=sys.stderr)
        print("\nAvailable sources:")
        list_sources()
        sys.exit(1)

    print(f"\nUpdating source [{source['id']}]: {source['name']}")
    print(f"Description: {source['description']}\n")

    # Step 2: Idempotency — skip if the source's conf.d file is already current.
    existing_timestamp = read_source_timestamp(confd_path(source))

    # Step 3: Fetch latest data from source
    fetch_func = source['fetch_func']
    domains, timestamp, metadata = fetch_func()

    if existing_timestamp and existing_timestamp == timestamp:
        print(f"\n  Already up to date (last update: {timestamp})")
        return 'skipped'
    if existing_timestamp:
        print("  Update available, proceeding...")
    else:
        print("  First run for this source...")

    # Step 7: Strip www prefix, apply exclusions, and remove duplicates
    print(f"  Processing {len(domains)} domains...")
    original_count = len(domains)

    # Strip www. prefix from all domains
    stripped_domains = []
    for domain in domains:
        if domain.startswith('www.'):
            stripped_domains.append(domain[4:])  # Remove 'www.' prefix
        else:
            stripped_domains.append(domain)

    # Apply exclusion list
    excluded_count = 0
    filtered_domains = []
    for domain in stripped_domains:
        domain_lower = domain.lower()
        if any(substr in domain_lower for substr in EXCLUDED_DOMAIN_SUBSTRINGS):
            excluded_count += 1
        else:
            filtered_domains.append(domain)
    if excluded_count > 0:
        print(f"  Excluded {excluded_count} domains matching exclusion list")

    # Remove duplicates while preserving order
    seen = set()
    unique_domains = []
    for domain in filtered_domains:
        if domain not in seen:
            seen.add(domain)
            unique_domains.append(domain)

    removed_count = original_count - len(unique_domains) - excluded_count
    if removed_count > 0:
        print(f"  Removed {removed_count} duplicate/www-prefixed domains")

    # Format domains using source's parse function
    parse_func = source['parse_func']
    formatted_lines = [parse_func(domain) for domain in unique_domains]
    formatted_domains = '\n'.join(formatted_lines)

    # Step 4: Write the source's conf.d file.
    path = confd_path(source)
    print(f"  Writing {path}...")
    try:
        write_source_file(source, formatted_domains, timestamp, len(unique_domains))
        print(f"  Successfully wrote {len(unique_domains)} domains\n")
        return 'updated'
    except Exception as e:
        print(f"  Error writing {path}: {e}", file=sys.stderr)
        sys.exit(1)

## Strip Managed Sources

def strip_managed_sources():
    """Delete all generated conf.d/ blocklist files. Manual domains kept inline in
    conf.yaml are untouched."""
    print("\nRemoving all generated blocklist files from conf.d/...\n")

    removed_sources = []
    for source in SOURCES:
        path = confd_path(source)
        try:
            os.remove(path)
        except FileNotFoundError:
            continue
        except Exception as e:
            print(f"  Error removing {path}: {e}", file=sys.stderr)
            sys.exit(1)
        removed_sources.append(source['name'])
        print(f"  ✓ Removed: {path}")

    if not removed_sources:
        print("  No generated blocklist files found.\n")
        return

    print(f"\n  Removed {len(removed_sources)} generated blocklist file(s).")
    print("  Any domains kept inline in conf.yaml are untouched.\n")

## Source Listing
def list_sources():
    """Display all available sources with their current status."""
    print("\nAvailable domain sources:\n")

    for source in SOURCES:
        print(f"  [{source['id']}] {source['name']}")
        print(f"      {source['description']}")

        path = confd_path(source)
        try:
            with open(path, 'r') as f:
                head = f.read(4096)
        except FileNotFoundError:
            print("      Status: Not yet generated (first run)")
            print(f"      File:   {path}")
            print()
            continue

        ts = re.search(r'# Last updated: ([0-9T:\-Z]+)', head)
        cnt = re.search(r'\((\d+) domains\)', head)
        if ts and cnt:
            print(f"      Last updated: {ts.group(1)} ({cnt.group(1)} domains)")
        elif ts:
            print(f"      Last updated: {ts.group(1)}")
        else:
            print("      Status: Generated (no header timestamp)")
        print(f"      File:   {path}")
        print()

    print("Usage:")
    print("  ./update_domains.py <number>  - Update a specific source")
    print("  ./update_domains.py all       - Update all sources")
    print("  ./update_domains.py strip     - Remove all managed sources\n")

## Update All Sources

def update_all_sources():
    """Update domains from all sources sequentially."""
    print("\nUpdating all domain sources...\n")
    print("=" * 60)

    success_count = 0
    error_count = 0
    skipped_count = 0

    for source in SOURCES:
        print(f"\n[{source['id']}/{len(SOURCES)}] Processing: {source['name']}")
        print("-" * 60)

        try:
            result = update_source(source['id'])
            if result == 'updated':
                success_count += 1
            elif result == 'skipped':
                skipped_count += 1
        except SystemExit as e:
            # update_source() calls sys.exit() on errors
            # Catch it and continue with next source
            error_count += 1
            print(f"  ⚠️  Error updating source {source['id']}, continuing with next source...")

    # Summary
    print("\n" + "=" * 60)
    print("Update Summary:")
    print(f"  ✓ Successfully updated: {success_count}")
    print(f"  ⊘ Already up to date: {skipped_count}")
    if error_count > 0:
        print(f"  ✗ Errors: {error_count}")
    print("=" * 60 + "\n")

## Main Entry Point

def main():
    """Main execution function with CLI argument parsing."""
    if len(sys.argv) == 1:
        # No arguments - list sources
        list_sources()
        return

    if len(sys.argv) != 2:
        progname = sys.argv[0]
        help_message = f"""Usage: {progname} [source_id|all|strip]
       {progname}          - List all sources
       {progname} all      - Update all sources
       {progname} strip    - Remove all managed domain sources"""
        print(help_message, file=sys.stderr)
        sys.exit(1)

    # Check for all command
    if sys.argv[1].lower() in ['all', '-all', '--all']:
        update_all_sources()
        return

    # Check for strip command
    if sys.argv[1].lower() == 'strip':
        strip_managed_sources()
        return

    # Parse source ID
    try:
        source_id = int(sys.argv[1])
    except ValueError:
        print(f"Error: Invalid source ID '{sys.argv[1]}'. Must be a number, 'all', or 'strip'.", file=sys.stderr)
        print("\nAvailable sources:")
        list_sources()
        sys.exit(1)

    # Update the specified source
    update_source(source_id)


if __name__ == "__main__":
    main()
